---
# tasks file for roles/proxmox_exporter
- name: Remove old pve exporter service if exists
  systemd:
    name: pve-exporter
    state: stopped
    enabled: false
  failed_when: false

- name: Create proxmox exporter directory
  file:
    path: /opt/proxmox-exporter
    state: directory
    mode: "0755"

- name: Create proxmox exporter config
  copy:
    dest: /opt/proxmox-exporter/config.yml
    mode: "0600"
    content: |
      server:
        port: {{ proxmox_exporter_port }}

      proxmox:
        url: "https://{{ proxmox_host }}:8006"
        token_id: "{{ proxmox_token_id }}"
        token_secret: "{{ proxmox_token_secret }}"
        verify_ssl: false


- name: Stop old pve-exporter service if exists
  systemd:
    name: pve-exporter
    state: stopped
    enabled: false
  failed_when: false

- name: Remove old proxmox exporter container
  community.docker.docker_container:
    name: proxmox-exporter
    state: absent
  failed_when: false

- name: Run proxmox exporter container
  community.docker.docker_container:
    name: proxmox-exporter
    image: ghcr.io/starttoaster/proxmox-exporter:latest
    restart_policy: always
    state: started
    recreate: true
    published_ports:
      - "{{ proxmox_exporter_port }}:{{ proxmox_exporter_port }}"
    env:
      PROXMOX_EXPORTER_LOG_LEVEL: "info"
      PROXMOX_EXPORTER_PROXMOX_API_INSECURE: "true"
      PROXMOX_EXPORTER_PROXMOX_ENDPOINTS: "https://{{ proxmox_host }}:8006/"
      PROXMOX_EXPORTER_PROXMOX_TOKEN: "{{ proxmox_token_secret }}"
      PROXMOX_EXPORTER_PROXMOX_TOKEN_ID: "{{ proxmox_token_id }}"
      PROXMOX_EXPORTER_SERVER_PORT: "{{ proxmox_exporter_port | string }}"
      PROXMOX_EXPORTER_SERVER_ADDR: "0.0.0.0"