---
# tasks file for roles/containered
- name: Install containerd
  apt:
    name: containerd
    state: present
    update_cache: true

- name: Create containerd config dir
  file:
    path: /etc/containerd
    state: directory

- name: Generate default containerd config
  shell: containerd config default > /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml

- name: Use systemd cgroup driver
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'

- name: Enable CRI plugin if disabled
  replace:
    path: /etc/containerd/config.toml
    regexp: 'disabled_plugins = \["cri"\]'
    replace: 'disabled_plugins = []'

- name: Restart and enable containerd
  systemd:
    name: containerd
    enabled: true
    state: restarted