---
- name: Prepare all Kubernetes nodes
  hosts: k8s
  become: true
  roles:
    - common
    - containerd
    - kubernetes
   
- name: Install Node Exporter
  hosts: node_exporter
  become: true
  roles:
    - node_exporter
    
- name: Init control-plane
  hosts: master
  become: true
  roles:
    - master


- name: Install Calico CNI
  hosts: master
  become: true
  roles:
    - calico


- name: Install kube-state-metrics
  hosts: master
  become: true
  roles:
    - kube_state_metrics

- name: Install Ingress-nginx
  hosts: master
  become: true
  roles:
    - ingress-nginx

- name: Install Docker for GitHub self-hosted runner
  hosts: master
  become: true
  roles:
    - docker_runner

- name: Join workers
  hosts: workers
  become: true
  roles:
    - worker

- name: Install Grafana Prometheus EFK
  hosts: monitoring
  become: true
  roles:
    - observability


- name: Configure Grafana dashboards
  hosts: monitoring-vm
  become: true

  vars_files:
    - vars/main.yml

  roles:
    - observability

- name: Install Proxmox exporter
  hosts: monitoring
  become: true
  vars_files:
    - vars/main.yml
  roles:
    - proxmox_exporter