---
- name: Prepare all Kubernetes nodes
  hosts: k8s
  become: true
  roles:
    - common
    - containerd
    - kubernetes
   

- name: Init control-plane
  hosts: master
  become: true
  roles:
    - master


- name: Install Calico CNI
  hosts: master
  become: true
  roles:
    - calico

- name: Install Ingress-nginx
  hosts: master
  become: true
  roles:
    - ingress-nginx

- name: Join workers
  hosts: workers
  become: true
  roles:
    - worker