---
# tasks file for roles/proxmox_api
# api do logowania sie na serwer proxmox
- name: Ensure Proxmox API user exists
  community.proxmox.proxmox_user:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_root_user }}"
    api_password: "{{ proxmox_root_password }}"
    userid: "{{ proxmox_api_user }}@{{ proxmox_api_realm }}"
    validate_certs: false
    state: present


- name: Login to Proxmox API
  uri:
    url: "https://{{ proxmox_api_host }}:8006/api2/json/access/ticket"
    method: POST
    validate_certs: false
    body_format: form-urlencoded
    body:
      username: "{{ proxmox_root_user }}"
      password: "{{ proxmox_root_password }}"
  register: proxmox_login

- name: Assign role (ACL via Proxmox API)
  uri:
    url: "https://{{ proxmox_api_host }}:8006/api2/json/access/acl"
    method: PUT
    validate_certs: false
    body_format: form-urlencoded
    headers:
      CSRFPreventionToken: "{{ proxmox_login.json.data.CSRFPreventionToken }}"
      Cookie: "PVEAuthCookie={{ proxmox_login.json.data.ticket }}"
    body:
      path: "{{ proxmox_acl_path }}"
      roles: "{{ proxmox_role }}"
      users: "{{ proxmox_api_user }}@{{ proxmox_api_realm }}"
      propagate: 1

- name: Create API token for user
  community.proxmox.proxmox_user:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_root_user }}"
    api_password: "{{ proxmox_root_password }}"
    validate_certs: false
    userid: "{{ proxmox_api_user }}@{{ proxmox_api_realm }}"
    tokens:
      - tokenid: "{{ proxmox_api_token_id }}"
        privsep: false
    state: present